## This file (example.sage) was *autogenerated* from example.tex with sagetex.sty version 2010/03/25 v2.2.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('example')
_do_ver_check_ = False
if _do_ver_check_ and sagetex.__version__.find('2010/03/25 v2.2.5') == -1:
 import sys
 print '{0}.sage was generated with sagetex.sty version 2010/03/25 v2.2.5,'.format( sys.argv[0].split('.')[0])
 print 'but is being processed by sagetex.py version {0}.'.format( ' '.join(sagetex.__version__.strip().strip('[').split()[0:2]))
 print 'SageTeX version mismatch! Exiting.'
 sys.exit(int(1))
try:
 _st_.inline(0, latex(number_of_partitions(1269)))
except:
 _st_.goboom(8)
try:
 _st_.plot(0, format='notprovided', _p_=plot(sin(x), x, 0, 2*pi))
except:
 _st_.goboom(14)
_st_.blockbegin()
try:
     f(x) = exp(x) * sin(2*x)
except:
 _st_.goboom(18)
_st_.blockend()
try:
 _st_.inline(1, latex(f(x)))
except:
 _st_.goboom(23)
try:
 _st_.inline(2, latex(diff(f, x, 2)(x)))
except:
 _st_.goboom(24)
try:
 _st_.plot(1, format='notprovided', _p_=plot(f, -1, 1))
except:
 _st_.goboom(29)
_st_.endofdoc()
